version: '3.8'

services:
  # MongoDB
  mongodb:
    image: mongo:6.0
    container_name: smart-shopping-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: smart-shopping
    volumes:
      - mongo-data:/data/db

  # Redis
  redis:
    image: redis:7-alpine
    container_name: smart-shopping-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: smart-shopping-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/smart-shopping?authSource=admin
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-super-secret-jwt-key-change-this
      JWT_EXPIRE: 7d
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./backend/uploads:/app/uploads

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: smart-shopping-frontend
    restart: always
    ports:
      - "3000:80"
    environment:
      REACT_APP_API_URL: http://localhost:5000/api
      REACT_APP_WEBSOCKET_URL: ws://localhost:5000
    depends_on:
      - backend

  # Nginx (Optional - for production)
  nginx:
    image: nginx:alpine
    container_name: smart-shopping-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend

volumes:
  mongo-data:
  redis-data: